//
//  MarsRoverViewController.swift
//  Desafio Beblue_LucasCordeiro
//
//  Created by Lucas Cordeiro on 03/03/19.
//  Copyright (c) 2019 Sparks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Lottie

protocol MarsRoverDisplayLogic: class {
    func displayMarsPhotos(viewModel: MarsRover.ListMarsRoverPhotos.ViewModel)
    func displayMarsPhotosPagination(viewModel: MarsRover.ListMarsRoverPhotos.ViewModel)
}

class MarsRoverViewController: UIViewController, MarsRoverDisplayLogic {

    //
    // MARK: - Scene Delegates -
    var interactor: MarsRoverBusinessLogic?
    var router: (NSObjectProtocol & MarsRoverRoutingLogic & MarsRoverDataPassing)?

    //
    // MARK: - Outlets -
    @IBOutlet weak var collectionView: UICollectionView!
    @IBOutlet weak var mainLoadingViewOutlet: LOTAnimationView!

    //
    // MARK: - Local Properties -
    private var marsRoverPhotos: [MarsRover.ListMarsRoverPhotos.ViewModel.MarsRoverPhoto] = []
    private let minNumberOfPhotos = 20

    //
    // MARK: - Routing -
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    //
    // MARK: - Life Cycle Methods -
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        configureCollectionViewCells()
        loadMarsRoversPhotos()
    }

    //
    // MARK: - Request Methods -
    func loadMarsRoversPhotos() {
        let request =
            MarsRover.ListMarsRoverPhotos.Request(filter: RoverPhotosFilter.curiosity.stringValue(), date: nil)
        mainLoadingViewOutlet.showAndPlay(loopAnimation: true)
        interactor?.listMarsRoverPhotos(request: request)
    }

    func paginate() {
        let request =
            MarsRover.PaginateMarsRoverPhotos.Request(filter: RoverPhotosFilter.curiosity.stringValue())
        interactor?.paginateMarsRoverPhotos(request: request)
    }

    //
    // MARK: - Display Methods -
    func displayMarsPhotos(viewModel: MarsRover.ListMarsRoverPhotos.ViewModel) {
        mainLoadingViewOutlet.hideAndStop()
        marsRoverPhotos = viewModel.marsRoverPhotos

        if marsRoverPhotos.count  < minNumberOfPhotos {
            paginate()
        }
        collectionView.reloadData()
    }

    func displayMarsPhotosPagination(viewModel: MarsRover.ListMarsRoverPhotos.ViewModel) {
        mainLoadingViewOutlet.hideAndStop()
        marsRoverPhotos.append(contentsOf: viewModel.marsRoverPhotos)

        if marsRoverPhotos.count  < minNumberOfPhotos {
            paginate()
        }
        collectionView.reloadData()
    }

    //
    // MARK: - Configure Methods -
    private func setup() {
        let viewController = self
        let interactor = MarsRoverInteractor()
        let presenter = MarsRoverPresenter()
        let router = MarsRoverRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    private func configureCollectionViewCells() {
        MarsRoverPhotoCollectionViewCell.register(inCollection: collectionView)
    }
}

//
// MARK: - UIScrollViewDelegate Extension -
extension MarsRoverViewController: UIScrollViewDelegate {
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let currentOffset = scrollView.contentOffset.y
        let maximumOffset = scrollView.contentSize.height - scrollView.frame.size.height

        if currentOffset >= maximumOffset * 0.65 {
            paginate()
        }
    }
}

//
// MARK: - UICollectionViewDelegate Extension -
extension MarsRoverViewController: UICollectionViewDelegate {
}

//
// MARK: - UICollectionViewDelegate Extension -
extension MarsRoverViewController: UICollectionViewDataSource {
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return marsRoverPhotos.count
    }

    func collectionView(_ collectionView: UICollectionView,
                        cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {

        guard let cell = collectionView.dequeueReusableCell(
            withReuseIdentifier: MarsRoverPhotoCollectionViewCell.classNameDescription(),
            for: indexPath) as? MarsRoverPhotoCollectionViewCell else {

                assertionFailure("No cell with " +
                    "\(MarsRoverPhotoCollectionViewCell.classNameDescription()) identifier registred")
                return UICollectionViewCell()
        }

        if indexPath.row < marsRoverPhotos.count {
            let url = marsRoverPhotos[indexPath.row].photosUrl
            cell.configureCell(photoUrl: url)
        }

        return cell
    }
}
