//
//  MarsRoverPresenter.swift
//  Desafio Beblue_LucasCordeiro
//
//  Created by Lucas Cordeiro on 03/03/19.
//  Copyright (c) 2019 Sparks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarsRoverPresentationLogic
{
  func presentSomething(response: MarsRover.Something.Response)
}

class MarsRoverPresenter: MarsRoverPresentationLogic
{
  weak var viewController: MarsRoverDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MarsRover.Something.Response)
  {
    let viewModel = MarsRover.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
