//
//  MarsRoverWorker.swift
//  Desafio Beblue_LucasCordeiro
//
//  Created by Lucas Cordeiro on 03/03/19.
//  Copyright (c) 2019 Sparks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ResponseHandler = (_ response: MarsRover.ListMarsRoverPhotos.Response) -> Void

class MarsRoverWorker {
    func listMarsRoverPhotos(filter: String,
                             date: String,
                             success: @escaping(ResponseHandler),
                             fail: @escaping(ResponseHandler)) {

        APIClientWorker.listMarsRoverPhotos(filter: filter, date: date) { (result) in
            if let validResult = try? result.unwrap() {
                success(MarsRover.ListMarsRoverPhotos.Response(photosInfo: validResult.photosInfo,
                                                               isError: false,
                                                               message: nil))
            } else {
                fail(MarsRover.ListMarsRoverPhotos.Response(photosInfo: nil,
                                                            isError: true,
                                                            message: "Result not found"))
            }
        }
    }
}
