//
//  MarsPhotosDetailPresenter.swift
//  Desafio Beblue_LucasCordeiro
//
//  Created by Lucas Cordeiro on 04/03/19.
//  Copyright (c) 2019 Sparks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarsPhotosDetailPresentationLogic {
    func presentPhotosInfo(response: MarsPhotosDetail.LoadPhotosInfo.Response)
    func presentNewButtonName(response: MarsPhotosDetail.ChangeButtonName.Response)
}

class MarsPhotosDetailPresenter: MarsPhotosDetailPresentationLogic {

    //
    // MARK: - Scene Properties -
    weak var viewController: MarsPhotosDetailDisplayLogic?

    //
    // MARK: - Present Methods -
    func presentPhotosInfo(response: MarsPhotosDetail.LoadPhotosInfo.Response) {
        guard let photoStringURL = response.photoInfo.imageSource,
            let photoURL = URL(string: photoStringURL) else {
                assertionFailure("No valid image source")
                return
        }
        guard let buttonName = response.photoInfo.camera?.name else {
            assertionFailure("No valid camera button")
            return
        }

        let viewModel = MarsPhotosDetail.LoadPhotosInfo.ViewModel(photosUrl: photoURL, buttonName: buttonName)
        viewController?.displayPhotosInfo(viewModel: viewModel)
    }

    func presentNewButtonName(response: MarsPhotosDetail.ChangeButtonName.Response) {

        let viewModel = MarsPhotosDetail.ChangeButtonName.ViewModel(buttonName: response.buttonName)
        viewController?.displayButtonName(viewModel: viewModel)
    }
}
