//
//  MarsPhotosDetailModels.swift
//  Desafio Beblue_LucasCordeiro
//
//  Created by Lucas Cordeiro on 04/03/19.
//  Copyright (c) 2019 Sparks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MarsPhotosDetail {

    enum LoadPhotosInfo {
        struct Request {
        }

        struct Response {
            let photoInfo: RoverPhotoInfo
        }

        struct ViewModel {
            let photosUrl: URL
            let buttonName: String
        }
    }

    enum ChangeButtonName {
        struct Request {
            let currentButtonName: String
        }
        struct Response {
            let buttonName: String
        }

        struct ViewModel {
            let buttonName: String
        }
    }
}
