//
//  MarsPhotosDetailInteractor.swift
//  Desafio Beblue_LucasCordeiro
//
//  Created by Lucas Cordeiro on 04/03/19.
//  Copyright (c) 2019 Sparks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MarsPhotosDetailBusinessLogic {
    func loadPhotosInfo(request: MarsPhotosDetail.LoadPhotosInfo.Request)
    func changeButtonName(request: MarsPhotosDetail.ChangeButtonName.Request)
}

protocol MarsPhotosDetailDataStore {
    var roverPhotoInfo: RoverPhotoInfo! { get set }
}

class MarsPhotosDetailInteractor: MarsPhotosDetailBusinessLogic, MarsPhotosDetailDataStore {

    //
    // MARK: - Scene Properties -
    var presenter: MarsPhotosDetailPresentationLogic?
    var worker: MarsPhotosDetailWorker?
    var roverPhotoInfo: RoverPhotoInfo!

    //
    // MARK: - Photos Info Methods -
    func loadPhotosInfo(request: MarsPhotosDetail.LoadPhotosInfo.Request) {
        let response = MarsPhotosDetail.LoadPhotosInfo.Response(photoInfo: roverPhotoInfo)
        presenter?.presentPhotosInfo(response: response)
    }

    func changeButtonName(request: MarsPhotosDetail.ChangeButtonName.Request) {

        var buttonName = ""
        let currentButtonName = request.currentButtonName
        if currentButtonName == roverPhotoInfo.camera?.name {
            buttonName = roverPhotoInfo.camera?.fullName ?? "No Full Name Found"
        } else if currentButtonName == roverPhotoInfo.camera?.fullName {
            buttonName = roverPhotoInfo.camera?.name ?? "No Short Name Found"
        } else {
            buttonName = "No Info Found"
        }
        let response = MarsPhotosDetail.ChangeButtonName.Response(buttonName: buttonName)
        presenter?.presentNewButtonName(response: response)
    }
}
